services:
  postgres:
    container_name: postgres-sql-task-tracker
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: task_tracker
    volumes:
        - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-task-tracker
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
  tasktracker-api:
    container_name: task-tracker-api
    image: tasktracker/tasktracker:1.0.0
    ports:
      - 8088:8088
    networks:
      - spring-demo
    depends_on:
      - postgres
  task-tracker-ui:
    container_name: task-tracker-ui
    image: task-tracker-ui:1.0.0
    ports:
      - 5173:80
    networks:
      - spring-demo
    depends_on:
        - tasktracker-api

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
