/* tslint:disable */
/* eslint-disable */
/**
 * Task Tracker API
 * Task Tracker API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: trnka.roman13@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommentRequest
 */
export interface CommentRequest {
    /**
     * 
     * @type {string}
     * @memberof CommentRequest
     */
    comment: string;
    /**
     * 
     * @type {string}
     * @memberof CommentRequest
     */
    taskId: string;
}

/**
 * Check if a given object implements the CommentRequest interface.
 */
export function instanceOfCommentRequest(value: object): value is CommentRequest {
    if (!('comment' in value) || value['comment'] === undefined) return false;
    if (!('taskId' in value) || value['taskId'] === undefined) return false;
    return true;
}

export function CommentRequestFromJSON(json: any): CommentRequest {
    return CommentRequestFromJSONTyped(json, false);
}

export function CommentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'comment': json['comment'],
        'taskId': json['taskId'],
    };
}

export function CommentRequestToJSON(value?: CommentRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'comment': value['comment'],
        'taskId': value['taskId'],
    };
}

