/* tslint:disable */
/* eslint-disable */
/**
 * Task Tracker API
 * Task Tracker API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: trnka.roman13@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserDTO } from './UserDTO';
import {
    UserDTOFromJSON,
    UserDTOFromJSONTyped,
    UserDTOToJSON,
} from './UserDTO';

/**
 * 
 * @export
 * @interface CommentResponse
 */
export interface CommentResponse {
    /**
     * 
     * @type {string}
     * @memberof CommentResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentResponse
     */
    comment?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentResponse
     */
    taskId?: string;
    /**
     * 
     * @type {Date}
     * @memberof CommentResponse
     */
    createdAt?: Date;
    /**
     * 
     * @type {UserDTO}
     * @memberof CommentResponse
     */
    createdBy?: UserDTO;
}

/**
 * Check if a given object implements the CommentResponse interface.
 */
export function instanceOfCommentResponse(value: object): value is CommentResponse {
    return true;
}

export function CommentResponseFromJSON(json: any): CommentResponse {
    return CommentResponseFromJSONTyped(json, false);
}

export function CommentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'comment': json['comment'] == null ? undefined : json['comment'],
        'taskId': json['taskId'] == null ? undefined : json['taskId'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'createdBy': json['createdBy'] == null ? undefined : UserDTOFromJSON(json['createdBy']),
    };
}

export function CommentResponseToJSON(value?: CommentResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'comment': value['comment'],
        'taskId': value['taskId'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'createdBy': UserDTOToJSON(value['createdBy']),
    };
}

