/* tslint:disable */
/* eslint-disable */
/**
 * Task Tracker API
 * Task Tracker API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: trnka.roman13@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommentResponse } from './CommentResponse';
import {
    CommentResponseFromJSON,
    CommentResponseFromJSONTyped,
    CommentResponseToJSON,
} from './CommentResponse';

/**
 * 
 * @export
 * @interface PageResponseCommentResponse
 */
export interface PageResponseCommentResponse {
    /**
     * 
     * @type {Array<CommentResponse>}
     * @memberof PageResponseCommentResponse
     */
    data?: Array<CommentResponse>;
    /**
     * 
     * @type {number}
     * @memberof PageResponseCommentResponse
     */
    pageNum?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseCommentResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseCommentResponse
     */
    count?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseCommentResponse
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the PageResponseCommentResponse interface.
 */
export function instanceOfPageResponseCommentResponse(value: object): value is PageResponseCommentResponse {
    return true;
}

export function PageResponseCommentResponseFromJSON(json: any): PageResponseCommentResponse {
    return PageResponseCommentResponseFromJSONTyped(json, false);
}

export function PageResponseCommentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageResponseCommentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(CommentResponseFromJSON)),
        'pageNum': json['pageNum'] == null ? undefined : json['pageNum'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'count': json['count'] == null ? undefined : json['count'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function PageResponseCommentResponseToJSON(value?: PageResponseCommentResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(CommentResponseToJSON)),
        'pageNum': value['pageNum'],
        'pageSize': value['pageSize'],
        'count': value['count'],
        'totalPages': value['totalPages'],
    };
}

