/* tslint:disable */
/* eslint-disable */
/**
 * Task Tracker API
 * Task Tracker API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: trnka.roman13@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ParticipantIdsRequest
 */
export interface ParticipantIdsRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof ParticipantIdsRequest
     */
    participantIds: Array<string>;
}

/**
 * Check if a given object implements the ParticipantIdsRequest interface.
 */
export function instanceOfParticipantIdsRequest(value: object): value is ParticipantIdsRequest {
    if (!('participantIds' in value) || value['participantIds'] === undefined) return false;
    return true;
}

export function ParticipantIdsRequestFromJSON(json: any): ParticipantIdsRequest {
    return ParticipantIdsRequestFromJSONTyped(json, false);
}

export function ParticipantIdsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ParticipantIdsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'participantIds': json['participantIds'],
    };
}

export function ParticipantIdsRequestToJSON(value?: ParticipantIdsRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'participantIds': value['participantIds'],
    };
}

